Update PluginCreatorPlugin.Build.cs
When I want to add current codes to my project (generate visual studio project files), it will appear error CS1729. After searching from the Internet, I found the solution in https://answers.unrealengine.com/questions/764146/unreal-build-tool-error-1.html worked:

In UE 4.16 engine switched from using ReadOnlyTargetRules from TargetInfo in constructor of your C# modules. In newer version you also have to call base contructor and pass that target(ReadOnlyTargetRules) here.